# Generated by Django 4.2 on 2024-02-05 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='review',
            name='Create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
