# Generated by Django 4.2 on 2024-02-20 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_review_product_alter_review_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Create_at',
        ),
        migrations.AddField(
            model_name='review',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
